# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmd" do
  desc "AI-assisted CLI that turns natural language into shell commands"
  homepage "https://github.com/pranjaltech/command"
  version "0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmd"

  on_macos do
    on_intel do
      url "https://github.com/pranjaltech/command/releases/download/0.2/cmd_0.2_darwin_amd64.tar.gz"
      sha256 "d5761dd272270027b1713191762c4f8c0112c91afb402aa7a3a371b2c425a9ff"
    end
    on_arm do
      url "https://github.com/pranjaltech/command/releases/download/0.2/cmd_0.2_darwin_arm64.tar.gz"
      sha256 "147e77c388ace28d9366f5c4ee34187692b963173d91557ac3489666cd1a2c73"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pranjaltech/command/releases/download/0.2/cmd_0.2_linux_amd64.tar.gz"
      sha256 "14ce7a99476ca4b3266341d1101112252ae4998be64efa16ea392fccea9993b3"
    end
    on_arm do
      url "https://github.com/pranjaltech/command/releases/download/0.2/cmd_0.2_linux_arm64.tar.gz"
      sha256 "b190591ef373b65f26e15d37d2e0fd381a0f8172ba46b48baba5f0ecc8c8c6b9"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cmd"]
    end
  end

  # No zap stanza required
end
