# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmd" do
  desc "AI-assisted CLI that turns natural language into shell commands"
  homepage "https://github.com/pranjaltech/command"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmd"

  on_macos do
    on_intel do
      url "https://github.com/pranjaltech/command/releases/download/0.1.2/cmd_0.1.2_darwin_amd64.tar.gz"
      sha256 "c377f9ec437109446954421d306bc66c3ebf31f8a7f3d55df1394a18c63d1554"
    end
    on_arm do
      url "https://github.com/pranjaltech/command/releases/download/0.1.2/cmd_0.1.2_darwin_arm64.tar.gz"
      sha256 "32f79452c4ebb4418484eab8521202f3e08e65c0d5c1ee832afe80e10f9d5957"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pranjaltech/command/releases/download/0.1.2/cmd_0.1.2_linux_amd64.tar.gz"
      sha256 "6ca066f40b6a5e282d55730196231689d429178c42b234e371458bc654eced1e"
    end
    on_arm do
      url "https://github.com/pranjaltech/command/releases/download/0.1.2/cmd_0.1.2_linux_arm64.tar.gz"
      sha256 "184778fb2a2c1ff513f9b484fd57f0b0fbea06c124dda8005c1ae0bbc174de2f"
    end
  end

  # No zap stanza required
end
