# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmd" do
  desc "AI-assisted CLI that turns natural language into shell commands"
  homepage "https://github.com/pranjaltech/command"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmd"

  on_macos do
    on_intel do
      url "https://github.com/pranjaltech/command/releases/download/0.1.3/cmd_0.1.3_darwin_amd64.tar.gz"
      sha256 "527bccd92b7468dde469a3616a8ad9934ff2ed5104a47392dc589e0ddc68358f"
    end
    on_arm do
      url "https://github.com/pranjaltech/command/releases/download/0.1.3/cmd_0.1.3_darwin_arm64.tar.gz"
      sha256 "1994b0c802dfe4e5aad981d645b14b963a89eecae250a7e1ce7a6911ca823795"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pranjaltech/command/releases/download/0.1.3/cmd_0.1.3_linux_amd64.tar.gz"
      sha256 "114da44968ad36bed1ff4f5341e328666bcdcbab0cf6a1cfd869e577168bf557"
    end
    on_arm do
      url "https://github.com/pranjaltech/command/releases/download/0.1.3/cmd_0.1.3_linux_arm64.tar.gz"
      sha256 "cb6a92c131aeb177a54e869ac0b2e5db8577fa55befd227f9f7e412513132525"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cmd"]
    end
  end

  # No zap stanza required
end
